included: # paths to include during linting. `--path` is ignored if present.
    - Sources

disabled_rules:
    - identifier_name
    - type_name

file_length:
  warning: 200
  error: 500
line_length: 130
function_parameter_count: 6
